CREATE TABLE `t_user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
	`name` VARCHAR(10) NULL DEFAULT NULL COMMENT '姓名',
	`age` INT(11) NULL DEFAULT NULL COMMENT '年龄',
	`flag` INT(11) NULL DEFAULT '0' COMMENT '1：删除',
	`create_by` INT(11) NULL DEFAULT NULL COMMENT '创建者id',
	`create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`update_by` INT(11) NULL DEFAULT NULL COMMENT '修改者id',
	`update_date` DATETIME NULL DEFAULT NULL COMMENT '修改时间',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=38
;
